//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Appli_KT2.Droid.services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IniciarSesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearPerfilOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarPerfilOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarPerfilOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPerfilOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerPlantelesOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerCarrerasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://localhost:50681/Service1.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IniciarSesionCompletedEventHandler IniciarSesionCompleted;
        
        /// <remarks/>
        public event CrearCuentaCompletedEventHandler CrearCuentaCompleted;
        
        /// <remarks/>
        public event CrearPerfilCompletedEventHandler CrearPerfilCompleted;
        
        /// <remarks/>
        public event ModificarPerfilCompletedEventHandler ModificarPerfilCompleted;
        
        /// <remarks/>
        public event EliminarPerfilCompletedEventHandler EliminarPerfilCompleted;
        
        /// <remarks/>
        public event ConsultarPerfilCompletedEventHandler ConsultarPerfilCompleted;
        
        /// <remarks/>
        public event consultarCompletedEventHandler consultarCompleted;
        
        /// <remarks/>
        public event obtenerPlantelesCompletedEventHandler obtenerPlantelesCompleted;
        
        /// <remarks/>
        public event obtenerCarrerasCompletedEventHandler obtenerCarrerasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/IniciarSesion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IniciarSesion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string user, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pass, out bool IniciarSesionResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IniciarSesionResultSpecified) {
            object[] results = this.Invoke("IniciarSesion", new object[] {
                        user,
                        pass});
            IniciarSesionResult = ((bool)(results[0]));
            IniciarSesionResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string user, string pass) {
            this.IniciarSesionAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string user, string pass, object userState) {
            if ((this.IniciarSesionOperationCompleted == null)) {
                this.IniciarSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarSesionOperationCompleted);
            }
            this.InvokeAsync("IniciarSesion", new object[] {
                        user,
                        pass}, this.IniciarSesionOperationCompleted, userState);
        }
        
        private void OnIniciarSesionOperationCompleted(object arg) {
            if ((this.IniciarSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarSesionCompleted(this, new IniciarSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CrearCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CrearCuenta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UsuarioClass usuario, out bool CrearCuentaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CrearCuentaResultSpecified) {
            object[] results = this.Invoke("CrearCuenta", new object[] {
                        usuario});
            CrearCuentaResult = ((bool)(results[0]));
            CrearCuentaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CrearCuentaAsync(UsuarioClass usuario) {
            this.CrearCuentaAsync(usuario, null);
        }
        
        /// <remarks/>
        public void CrearCuentaAsync(UsuarioClass usuario, object userState) {
            if ((this.CrearCuentaOperationCompleted == null)) {
                this.CrearCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearCuentaOperationCompleted);
            }
            this.InvokeAsync("CrearCuenta", new object[] {
                        usuario}, this.CrearCuentaOperationCompleted, userState);
        }
        
        private void OnCrearCuentaOperationCompleted(object arg) {
            if ((this.CrearCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearCuentaCompleted(this, new CrearCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/CrearPerfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CrearPerfil([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UsuarioClass usuario, out bool CrearPerfilResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CrearPerfilResultSpecified) {
            object[] results = this.Invoke("CrearPerfil", new object[] {
                        usuario});
            CrearPerfilResult = ((bool)(results[0]));
            CrearPerfilResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CrearPerfilAsync(UsuarioClass usuario) {
            this.CrearPerfilAsync(usuario, null);
        }
        
        /// <remarks/>
        public void CrearPerfilAsync(UsuarioClass usuario, object userState) {
            if ((this.CrearPerfilOperationCompleted == null)) {
                this.CrearPerfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearPerfilOperationCompleted);
            }
            this.InvokeAsync("CrearPerfil", new object[] {
                        usuario}, this.CrearPerfilOperationCompleted, userState);
        }
        
        private void OnCrearPerfilOperationCompleted(object arg) {
            if ((this.CrearPerfilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearPerfilCompleted(this, new CrearPerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ModificarPerfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarPerfil([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UsuarioClass usuario, out bool ModificarPerfilResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ModificarPerfilResultSpecified) {
            object[] results = this.Invoke("ModificarPerfil", new object[] {
                        usuario});
            ModificarPerfilResult = ((bool)(results[0]));
            ModificarPerfilResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ModificarPerfilAsync(UsuarioClass usuario) {
            this.ModificarPerfilAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ModificarPerfilAsync(UsuarioClass usuario, object userState) {
            if ((this.ModificarPerfilOperationCompleted == null)) {
                this.ModificarPerfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarPerfilOperationCompleted);
            }
            this.InvokeAsync("ModificarPerfil", new object[] {
                        usuario}, this.ModificarPerfilOperationCompleted, userState);
        }
        
        private void OnModificarPerfilOperationCompleted(object arg) {
            if ((this.ModificarPerfilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarPerfilCompleted(this, new ModificarPerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/EliminarPerfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarPerfil(int cveUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cveUsuarioSpecified, int cvePersona, [System.Xml.Serialization.XmlIgnoreAttribute()] bool cvePersonaSpecified, out bool EliminarPerfilResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool EliminarPerfilResultSpecified) {
            object[] results = this.Invoke("EliminarPerfil", new object[] {
                        cveUsuario,
                        cveUsuarioSpecified,
                        cvePersona,
                        cvePersonaSpecified});
            EliminarPerfilResult = ((bool)(results[0]));
            EliminarPerfilResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void EliminarPerfilAsync(int cveUsuario, bool cveUsuarioSpecified, int cvePersona, bool cvePersonaSpecified) {
            this.EliminarPerfilAsync(cveUsuario, cveUsuarioSpecified, cvePersona, cvePersonaSpecified, null);
        }
        
        /// <remarks/>
        public void EliminarPerfilAsync(int cveUsuario, bool cveUsuarioSpecified, int cvePersona, bool cvePersonaSpecified, object userState) {
            if ((this.EliminarPerfilOperationCompleted == null)) {
                this.EliminarPerfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarPerfilOperationCompleted);
            }
            this.InvokeAsync("EliminarPerfil", new object[] {
                        cveUsuario,
                        cveUsuarioSpecified,
                        cvePersona,
                        cvePersonaSpecified}, this.EliminarPerfilOperationCompleted, userState);
        }
        
        private void OnEliminarPerfilOperationCompleted(object arg) {
            if ((this.EliminarPerfilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarPerfilCompleted(this, new EliminarPerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ConsultarPerfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UsuarioClass ConsultarPerfil([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string user, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pass) {
            object[] results = this.Invoke("ConsultarPerfil", new object[] {
                        user,
                        pass});
            return ((UsuarioClass)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPerfilAsync(string user, string pass) {
            this.ConsultarPerfilAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void ConsultarPerfilAsync(string user, string pass, object userState) {
            if ((this.ConsultarPerfilOperationCompleted == null)) {
                this.ConsultarPerfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPerfilOperationCompleted);
            }
            this.InvokeAsync("ConsultarPerfil", new object[] {
                        user,
                        pass}, this.ConsultarPerfilOperationCompleted, userState);
        }
        
        private void OnConsultarPerfilOperationCompleted(object arg) {
            if ((this.ConsultarPerfilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPerfilCompleted(this, new ConsultarPerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/consultar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NotificacionClass consultar() {
            object[] results = this.Invoke("consultar", new object[0]);
            return ((NotificacionClass)(results[0]));
        }
        
        /// <remarks/>
        public void consultarAsync() {
            this.consultarAsync(null);
        }
        
        /// <remarks/>
        public void consultarAsync(object userState) {
            if ((this.consultarOperationCompleted == null)) {
                this.consultarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarOperationCompleted);
            }
            this.InvokeAsync("consultar", new object[0], this.consultarOperationCompleted, userState);
        }
        
        private void OnconsultarOperationCompleted(object arg) {
            if ((this.consultarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarCompleted(this, new consultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/obtenerPlanteles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WebServiceAppli_KT.Modelo")]
        public PlantelesESClass[] obtenerPlanteles() {
            object[] results = this.Invoke("obtenerPlanteles", new object[0]);
            return ((PlantelesESClass[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerPlantelesAsync() {
            this.obtenerPlantelesAsync(null);
        }
        
        /// <remarks/>
        public void obtenerPlantelesAsync(object userState) {
            if ((this.obtenerPlantelesOperationCompleted == null)) {
                this.obtenerPlantelesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerPlantelesOperationCompleted);
            }
            this.InvokeAsync("obtenerPlanteles", new object[0], this.obtenerPlantelesOperationCompleted, userState);
        }
        
        private void OnobtenerPlantelesOperationCompleted(object arg) {
            if ((this.obtenerPlantelesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerPlantelesCompleted(this, new obtenerPlantelesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/obtenerCarreras", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WebServiceAppli_KT.Modelo")]
        public CarrerasESClass[] obtenerCarreras() {
            object[] results = this.Invoke("obtenerCarreras", new object[0]);
            return ((CarrerasESClass[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerCarrerasAsync() {
            this.obtenerCarrerasAsync(null);
        }
        
        /// <remarks/>
        public void obtenerCarrerasAsync(object userState) {
            if ((this.obtenerCarrerasOperationCompleted == null)) {
                this.obtenerCarrerasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerCarrerasOperationCompleted);
            }
            this.InvokeAsync("obtenerCarreras", new object[0], this.obtenerCarrerasOperationCompleted, userState);
        }
        
        private void OnobtenerCarrerasOperationCompleted(object arg) {
            if ((this.obtenerCarrerasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerCarrerasCompleted(this, new obtenerCarrerasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WebServiceAppli_KT.Modelo")]
    public partial class UsuarioClass {
        
        private string contraseniaField;
        
        private int cveUsuarioField;
        
        private bool cveUsuarioFieldSpecified;
        
        private string estatusField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private string nombreUsuarioField;
        
        private PersonaClass personaField;
        
        private string rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                this.contraseniaField = value;
            }
        }
        
        /// <remarks/>
        public int cveUsuario {
            get {
                return this.cveUsuarioField;
            }
            set {
                this.cveUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cveUsuarioSpecified {
            get {
                return this.cveUsuarioFieldSpecified;
            }
            set {
                this.cveUsuarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PersonaClass persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WebServiceAppli_KT.Modelo")]
    public partial class PersonaClass {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string coloniaField;
        
        private string correoElectronicoField;
        
        private string curpField;
        
        private int cvePersonaField;
        
        private bool cvePersonaFieldSpecified;
        
        private int estadoCivilField;
        
        private bool estadoCivilFieldSpecified;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private string municipioField;
        
        private string nacionalidadField;
        
        private string nombreField;
        
        private string numeroTelefonoField;
        
        private string perfilField;
        
        private string rfcField;
        
        private string sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string curp {
            get {
                return this.curpField;
            }
            set {
                this.curpField = value;
            }
        }
        
        /// <remarks/>
        public int cvePersona {
            get {
                return this.cvePersonaField;
            }
            set {
                this.cvePersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cvePersonaSpecified {
            get {
                return this.cvePersonaFieldSpecified;
            }
            set {
                this.cvePersonaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoCivilSpecified {
            get {
                return this.estadoCivilFieldSpecified;
            }
            set {
                this.estadoCivilFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numeroTelefono {
            get {
                return this.numeroTelefonoField;
            }
            set {
                this.numeroTelefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WebServiceAppli_KT.Modelo")]
    public partial class CarrerasESClass {
        
        private int activaField;
        
        private bool activaFieldSpecified;
        
        private string campoAmplio2016Field;
        
        private string campoAmplioAnteriorField;
        
        private string campoEspecifico2016Field;
        
        private string campoEspecificoAnteriorField;
        
        private string claveCarreraField;
        
        private int idCarreraESField;
        
        private bool idCarreraESFieldSpecified;
        
        private string nivelField;
        
        private string nombreCarreraESField;
        
        private PlantelesESClass plantelESField;
        
        /// <remarks/>
        public int activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activaSpecified {
            get {
                return this.activaFieldSpecified;
            }
            set {
                this.activaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string campoAmplio2016 {
            get {
                return this.campoAmplio2016Field;
            }
            set {
                this.campoAmplio2016Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string campoAmplioAnterior {
            get {
                return this.campoAmplioAnteriorField;
            }
            set {
                this.campoAmplioAnteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string campoEspecifico2016 {
            get {
                return this.campoEspecifico2016Field;
            }
            set {
                this.campoEspecifico2016Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string campoEspecificoAnterior {
            get {
                return this.campoEspecificoAnteriorField;
            }
            set {
                this.campoEspecificoAnteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveCarrera {
            get {
                return this.claveCarreraField;
            }
            set {
                this.claveCarreraField = value;
            }
        }
        
        /// <remarks/>
        public int idCarreraES {
            get {
                return this.idCarreraESField;
            }
            set {
                this.idCarreraESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCarreraESSpecified {
            get {
                return this.idCarreraESFieldSpecified;
            }
            set {
                this.idCarreraESFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreCarreraES {
            get {
                return this.nombreCarreraESField;
            }
            set {
                this.nombreCarreraESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PlantelesESClass plantelES {
            get {
                return this.plantelESField;
            }
            set {
                this.plantelESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WebServiceAppli_KT.Modelo")]
    public partial class PlantelesESClass {
        
        private string oPDField;
        
        private int activoField;
        
        private bool activoFieldSpecified;
        
        private string claveInstitucionField;
        
        private string clavePlantelField;
        
        private DetallePlantelClass detallePlantelField;
        
        private int idPlantelesESField;
        
        private bool idPlantelesESFieldSpecified;
        
        private string municipioField;
        
        private string nivelAgrupadoField;
        
        private string nombreInstitucionEsField;
        
        private string nombrePlantelESField;
        
        private string sostenimientoField;
        
        private string subsistemaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OPD {
            get {
                return this.oPDField;
            }
            set {
                this.oPDField = value;
            }
        }
        
        /// <remarks/>
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInstitucion {
            get {
                return this.claveInstitucionField;
            }
            set {
                this.claveInstitucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clavePlantel {
            get {
                return this.clavePlantelField;
            }
            set {
                this.clavePlantelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DetallePlantelClass detallePlantel {
            get {
                return this.detallePlantelField;
            }
            set {
                this.detallePlantelField = value;
            }
        }
        
        /// <remarks/>
        public int idPlantelesES {
            get {
                return this.idPlantelesESField;
            }
            set {
                this.idPlantelesESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPlantelesESSpecified {
            get {
                return this.idPlantelesESFieldSpecified;
            }
            set {
                this.idPlantelesESFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nivelAgrupado {
            get {
                return this.nivelAgrupadoField;
            }
            set {
                this.nivelAgrupadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreInstitucionEs {
            get {
                return this.nombreInstitucionEsField;
            }
            set {
                this.nombreInstitucionEsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombrePlantelES {
            get {
                return this.nombrePlantelESField;
            }
            set {
                this.nombrePlantelESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sostenimiento {
            get {
                return this.sostenimientoField;
            }
            set {
                this.sostenimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subsistema {
            get {
                return this.subsistemaField;
            }
            set {
                this.subsistemaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WebServiceAppli_KT.Modelo")]
    public partial class DetallePlantelClass {
        
        private string costosField;
        
        private int cveDetallePlantelField;
        
        private bool cveDetallePlantelFieldSpecified;
        
        private System.DateTime fechasField;
        
        private bool fechasFieldSpecified;
        
        private string imagenPlantelField;
        
        private string latitudField;
        
        private string logoPlantelField;
        
        private string longitudField;
        
        private string nivelEstudioField;
        
        private string requisitosField;
        
        private string reseñaField;
        
        private string ubicacionField;
        
        private string urlVinculacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string costos {
            get {
                return this.costosField;
            }
            set {
                this.costosField = value;
            }
        }
        
        /// <remarks/>
        public int cveDetallePlantel {
            get {
                return this.cveDetallePlantelField;
            }
            set {
                this.cveDetallePlantelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cveDetallePlantelSpecified {
            get {
                return this.cveDetallePlantelFieldSpecified;
            }
            set {
                this.cveDetallePlantelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechas {
            get {
                return this.fechasField;
            }
            set {
                this.fechasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechasSpecified {
            get {
                return this.fechasFieldSpecified;
            }
            set {
                this.fechasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imagenPlantel {
            get {
                return this.imagenPlantelField;
            }
            set {
                this.imagenPlantelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string logoPlantel {
            get {
                return this.logoPlantelField;
            }
            set {
                this.logoPlantelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nivelEstudio {
            get {
                return this.nivelEstudioField;
            }
            set {
                this.nivelEstudioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string requisitos {
            get {
                return this.requisitosField;
            }
            set {
                this.requisitosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string reseña {
            get {
                return this.reseñaField;
            }
            set {
                this.reseñaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string urlVinculacion {
            get {
                return this.urlVinculacionField;
            }
            set {
                this.urlVinculacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WebServiceAppli_KT.Modelo")]
    public partial class MediosEnvioClass {
        
        private int cveMedioEnvioField;
        
        private bool cveMedioEnvioFieldSpecified;
        
        private string estatusField;
        
        private string nombreField;
        
        /// <remarks/>
        public int cveMedioEnvio {
            get {
                return this.cveMedioEnvioField;
            }
            set {
                this.cveMedioEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cveMedioEnvioSpecified {
            get {
                return this.cveMedioEnvioFieldSpecified;
            }
            set {
                this.cveMedioEnvioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WebServiceAppli_KT.Modelo")]
    public partial class NotificacionClass {
        
        private string audienciaField;
        
        private string categorizacionField;
        
        private string colorSemaforizacionField;
        
        private int cveNotificacionesField;
        
        private bool cveNotificacionesFieldSpecified;
        
        private MediosEnvioClass medioDifusionField;
        
        private string responsableField;
        
        private string textoField;
        
        private string tipoNotificacionField;
        
        private string tituloField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string audiencia {
            get {
                return this.audienciaField;
            }
            set {
                this.audienciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string categorizacion {
            get {
                return this.categorizacionField;
            }
            set {
                this.categorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string colorSemaforizacion {
            get {
                return this.colorSemaforizacionField;
            }
            set {
                this.colorSemaforizacionField = value;
            }
        }
        
        /// <remarks/>
        public int cveNotificaciones {
            get {
                return this.cveNotificacionesField;
            }
            set {
                this.cveNotificacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cveNotificacionesSpecified {
            get {
                return this.cveNotificacionesFieldSpecified;
            }
            set {
                this.cveNotificacionesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MediosEnvioClass medioDifusion {
            get {
                return this.medioDifusionField;
            }
            set {
                this.medioDifusionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string responsable {
            get {
                return this.responsableField;
            }
            set {
                this.responsableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipoNotificacion {
            get {
                return this.tipoNotificacionField;
            }
            set {
                this.tipoNotificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void IniciarSesionCompletedEventHandler(object sender, IniciarSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniciarSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniciarSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool IniciarSesionResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool IniciarSesionResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CrearCuentaCompletedEventHandler(object sender, CrearCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool CrearCuentaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CrearCuentaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CrearPerfilCompletedEventHandler(object sender, CrearPerfilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearPerfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearPerfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool CrearPerfilResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CrearPerfilResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ModificarPerfilCompletedEventHandler(object sender, ModificarPerfilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarPerfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarPerfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool ModificarPerfilResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool ModificarPerfilResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EliminarPerfilCompletedEventHandler(object sender, EliminarPerfilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarPerfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarPerfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool EliminarPerfilResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool EliminarPerfilResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarPerfilCompletedEventHandler(object sender, ConsultarPerfilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPerfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPerfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void consultarCompletedEventHandler(object sender, consultarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NotificacionClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NotificacionClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void obtenerPlantelesCompletedEventHandler(object sender, obtenerPlantelesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerPlantelesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerPlantelesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PlantelesESClass[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlantelesESClass[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void obtenerCarrerasCompletedEventHandler(object sender, obtenerCarrerasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerCarrerasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerCarrerasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CarrerasESClass[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CarrerasESClass[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591